version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: .
      dockerfile: Backend.Courses.Api/Dockerfile
    container_name: backend-courses-api
    ports:
      - "5001:8080"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MongoSettings__DatabaseName=CoursesDb

volumes:
  mongo_data:
